import { describe, test, expect, afterAll } from "bun:test";
import { saveBufferAsImage } from "../../../src/utils/image.ts";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { rm, stat } from "node:fs/promises";

const TEST_DIR = join(tmpdir(), `opds-image-test-${Date.now()}`);

// Valid 1x1 red PNG (generated by ImageMagick)
const VALID_PNG = Buffer.from([
  0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d, 0x49, 0x48, 0x44, 0x52,
  0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x01, 0x03, 0x00, 0x00, 0x00, 0x25, 0xdb, 0x56,
  0xca, 0x00, 0x00, 0x00, 0x06, 0x50, 0x4c, 0x54, 0x45, 0xff, 0x00, 0x00, 0xff, 0xff, 0xff, 0x41,
  0x1d, 0x34, 0x11, 0x00, 0x00, 0x00, 0x0a, 0x49, 0x44, 0x41, 0x54, 0x08, 0xd7, 0x63, 0x60, 0x00,
  0x00, 0x00, 0x02, 0x00, 0x01, 0xe2, 0x21, 0xbc, 0x33, 0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4e,
  0x44, 0xae, 0x42, 0x60, 0x82,
]);

afterAll(async () => {
  await rm(TEST_DIR, { recursive: true, force: true }).catch(() => {});
});

describe("utils/image", () => {
  describe("saveBufferAsImage", () => {
    test("saves valid PNG buffer to file", async () => {
      const destPath = join(TEST_DIR, "valid.jpg");
      const result = await saveBufferAsImage(VALID_PNG, destPath, 100);

      expect(result).toBe(true);
      const fileStat = await stat(destPath);
      expect(fileStat.size).toBeGreaterThan(0);
    });

    test("creates parent directories if needed", async () => {
      const destPath = join(TEST_DIR, "nested", "deep", "dir", "image.jpg");
      const result = await saveBufferAsImage(VALID_PNG, destPath, 100);

      expect(result).toBe(true);
      const fileStat = await stat(destPath);
      expect(fileStat.isFile()).toBe(true);
    });

    test("respects max size parameter", async () => {
      const destPath = join(TEST_DIR, "sized.jpg");
      const result = await saveBufferAsImage(VALID_PNG, destPath, 50);

      expect(result).toBe(true);
    });

    test("returns false for invalid buffer", async () => {
      const destPath = join(TEST_DIR, "invalid.jpg");
      const invalidBuffer = Buffer.from("not an image");
      const result = await saveBufferAsImage(invalidBuffer, destPath, 100);

      expect(result).toBe(false);
    });

    test("returns false for empty buffer", async () => {
      const destPath = join(TEST_DIR, "empty.jpg");
      const result = await saveBufferAsImage(Buffer.alloc(0), destPath, 100);

      expect(result).toBe(false);
    });
  });
});
